// Generated by CoffeeScript 1.8.0
(function() {
  module.exports = function(grunt) {
    grunt.initConfig({
      imagemin: {
        build: {
          options: {
            optimizationLevel: 3
          },
          files: [
            {
              expand: true,
              cwd: '.assets/',
              src: ['**/*.{png,jpg,gif}', '**/**/*.{png,jpg,gif}', '**/**/**/*.{png,jpg,gif}'],
              dest: 'assets/'
            }
          ]
        }
      },
      uglify: {
        build: {
          options: {
            mangle: true,
            compress: {
              drop_console: true
            }
          },
          files: [
            {
              expand: true,
              cwd: '.assets/',
              src: ['*.js', '!*.min.js', '**/*.js', '!**/*.min.js', '**/**/*.js', '!**/**/*.min.js', '**/**/**/*.js', '!**/**/**/*.min.js'],
              dest: 'assets/',
              ext: '.js'
            }
          ]
        }
      },
      cssmin: {
        build: {
          options: {
            advanced: false,
            compatibility: true,
            processImport: false,
            shorthandCompacting: false
          },
          files: [
            {
              expand: true,
              cwd: '.assets/',
              src: ['*.css', '!*.min.css', '**/*.css', '!**/*.min.css', '**/**/*.css', '!**/**/*.min.css', '**/**/**/*.css', '!**/**/**/*.min.css'],
              dest: 'assets/'
            }
          ]
        }
      },
      watch: {
        configFiles: {
          files: 'Gruntfile.js',
          options: {
            reload: true
          }
        }
      }
    });
    grunt.loadNpmTasks('grunt-contrib-cssmin');
    grunt.loadNpmTasks('grunt-contrib-imagemin');
    grunt.loadNpmTasks('grunt-contrib-uglify');
    grunt.loadNpmTasks('grunt-contrib-watch');
    grunt.registerTask('build', ['uglify:build', 'cssmin:build']);
    grunt.registerTask('css', ['cssmin:build']);
    return grunt.registerTask('deploy', ['imagemin:build', 'uglify:build', 'cssmin:build']);
  };

}).call(this);

//# sourceMappingURL=Gruntfile.js.map
